apiVersion: v1
kind: Service
metadata:
  name: factory-api-db-service
  labels:
    app: factory-api-db-service
spec:
  selector:
    app: factory-api-db
  ports:
    - port: 3306
      targetPort: 3306